---
title: Visualização de dados com R
subtitle: Aula 1 - Introdução a visualização de dados
author: Marcus Ramalho
format: 
    revealjs: 
        incremental: true  
        transition: slide
        background-transition: fade
        theme: dark
date: today
footer: Universidade Federal Fluminense - Programa de formação de executivos - Ciência de dados
---

```{r}
library(tidyverse)
```

## O curso {auto-animate=true}

Aula 1

-   Tipos de gráfico por variável
-   Escalas
-   Gráficos no R
-   ggplot2
-   esquisse - ggplot builder
-   Exemplos
-   Exercícios de fixação
-   Tarefa com nota

## O que são gráficos? {.center}

::: {layout-ncol=2}

-   Uma forma de comunicação.

-   Uma forma de análise.

-   Uma forma de exploração de dados.

-   Gráficos são uma forma de visualização de dados.

```{r}
# Using median
mpg %>%
    mutate(class = fct_reorder(class, hwy, .fun = "median")) %>%
    ggplot(aes(x = reorder(class, hwy), y = hwy, fill = class)) +
    geom_boxplot() +
    xlab("class") +
    theme(legend.position = "none") +
    ylab("Milhas por galão") +
    xlab("Moldelo") +
    ggtitle("Milhas por galão por modelo")

# Using number of observation per group
mpg %>%
    mutate(class = fct_reorder(class, hwy, .fun = "length")) %>%
    ggplot(aes(x = class, y = hwy, fill = class)) +
    geom_boxplot() +
    xlab("class") +
    theme(legend.position = "none") +
    ylab("Milhas por galão") +
    xlab("Moldelo") +
    ggtitle("Milhas por galão por modelo")
```

:::